### ISSUE TITLE
SLAM with a video file

### ISSUE THREAD

**Issue by aliwaqas333** [LMWafer/orb-slam-3-ready#1]
Can someone guide me to try this with a video file .mp4 file ?

**Comment by LMWafer** [comment]
You may want to:

1. Create an [Opencv's `cv::VideoCapture`](https://docs.opencv.org/3.4/d8/dfe/classcv_1_1VideoCapture.html#a949d90b766ba42a6a93fe23a67785951) object to iterate over the frames of a `.mp4` file with its [`read` function](https://docs.opencv.org/3.4/d8/dfe/classcv_1_1VideoCapture.html#a473055e77dd7faa4d26d686226b292c1);
2. Create an `ORB_SLAM3::System` [configured in monocular](https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/4452a3c4ab75b1cde34e5505a36ec3f9edcdc4c4/Examples/Monocular/mono_realsense_D435i.cc#L210). Make sure you pass parameters consistent with the camera that shot the `.mp4`. This is done with the proper `.yaml` filepath for the `const string &strSettingsFile` argument of `ORB_SLAM3::System` constructor;
3. [Track your image](https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/4452a3c4ab75b1cde34e5505a36ec3f9edcdc4c4/Examples/Monocular/mono_realsense_D435i.cc#L279) within a loop depending on both the `cv::ideoCapture` (here, `cap`) and the `ORB_SLAM3::System`. Something like `while (!SLAM.isShutDown() && cap.isOpened())` !
